<?php
$db['member_auth']    = array (
    'columns'           => array (        
        'auth_id'     => array (
            'type'      => 'int',
            'required'  => true,
            'pkey'      => true,
            'extra'     => 'auto_increment',
            'label'     => app::get('b2c')->_('会员认证ID'),
            'width'     => 80,
            'editable'  => false,
			'in_list' => true,
			'default_in_list' => true,
            'order' => 10,
        ),
        'member_id'     => array (
            'type'      => 'table:members',
            'required'  => true,
            'label'     => app::get('b2c')->_('会员ID'),
            'width'     => 80,   
            'editable'  => true,
			'in_list' => true,
			'default_in_list' => true,
            'order' => 20,
        ),
        'real_name'       => array (
            'type'      => 'varchar(50)',       
            'label'     => app::get('b2c')->_('真实姓名'),
            'width'     => 60, 
			'in_list' => true,
			'default_in_list' => true,
            'order' => 30,
        ),
        'identity_num'       => array (
            'type'      => 'varchar(32)',
            'label'     => app::get('b2c')->_('身份证号'),         
            'width'     => 70, 
			'in_list' => true,
			'default_in_list' => true,
            'order' => 40,		
        ),
         'is_checked'       => array (
            'type'      =>array(
                0=>app::get('b2c')->_('未审核'),
                1=>app::get('b2c')->_('审核失败'),
				2=>app::get('b2c')->_('审核成功'),
            ),
            'label'     => app::get('b2c')->_('审核是否通过'),  
            'default'  => '0',
            'width'     => 70, 
			'in_list' => true,
			'default_in_list' => true,
            'order' => 50,		
        ),
         'image_id'       => array (
            'type'      => 'char(32)',
            'label'     => app::get('b2c')->_('上传图片id'),          
            'width'     => 70, 
			'in_list' => false,
			'default_in_list' => false,
        ),
         'upimage'       => array (
            'type'      => 'varchar(255)',
            'label'     => app::get('b2c')->_('上传图片'),           
            'width'     => 70,        
        ),
         'uptime'       => array (
            'type'      => 'time',
            'label'     => app::get('b2c')->_('申请时间'),       
            'width'     => 100, 
			'in_list' => true,
			'default_in_list' => true,
            'order' => 60,
        ),
         'checktime'       => array (
            'type'      => 'time',
            'label'     => app::get('b2c')->_('审核时间'),       
            'width'     => 70,
			'in_list' => false,
			'default_in_list' => false,
        ),
		  'remark'       => array (
            'type'      => 'varchar(225)',
            'label'     => app::get('b2c')->_('审核备注/说明'),       
            'width'     => 70,
			'in_list' => true,
			'default_in_list' => false,
        ),
    ),
    'index'  => array (
        'member_id' => array (
            'columns'   => array (
                0   => 'member_id',
            ),
        ),
    ),
    'engine' => 'innodb',
	'version'=>'$Rev: 23423423 $',
    'comment' => app::get('b2c')->_('会员认证表'),
);
